version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
