[package]
name = "oort"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rapier2d-f64 = { version = "0.9", features = ["wasm-bindgen"] }
crossbeam = "0.8"
oorandom = "11.1.3"
wasm-bindgen = "0.2.74"
js-sys = "0.3.51"
nalgebra = "0.27.1"
console_error_panic_hook = "0.1.6"
rand = "*"
getrandom = { version = "0.2", features = ["js"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }
lazy_static = "*"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'HtmlCanvasElement',
  'Node',
  'Window',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlShader',
  'WebGlUniformLocation',
  'KeyboardEvent',
  'console',
]

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[profile.dev.package.'*']
opt-level = 3

[[bench]]
name = "bullets"
harness = false
