[package]
name = "oort"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rapier2d-f64 = { version = "0.9", features = ["wasm-bindgen"] }
crossbeam = "0.8"
oorandom = "11.1.3"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3.51"
nalgebra = "0.27.1"
console_error_panic_hook = "0.1.6"
rand = "*"
getrandom = { version = "0.2", features = ["js"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }
lazy_static = "*"
console_log = "0.2.0"
log = "0.4"
rhai = { version = "1.0", features = ["internals"] }
test-env-log = "0.2"
env_logger = "0.9"
smartstring = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
no-comment = "0.0.3"
flate2 = "1.0.20"
rbtag = "0.3.0"
chrono = "0.4"
petname = "1.1.0"
rand_chacha = "0.3.1"
rand_seeder = "0.2.2"
regex = "1.5"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'HtmlCanvasElement',
  'Node',
  'Window',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGl2RenderingContext',
  'WebGlShader',
  'WebGlUniformLocation',
  'KeyboardEvent',
  'console',
  'Storage',
  'WheelEvent',
]

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[profile.dev.package.'*']
opt-level = 3

[package.metadata.wasm-pack.profile.profiling]
debug = 1
wasm-opt = false

[[bench]]
name = "bullets"
harness = false
