[workspace]

members = [
    "simulator",
    "worker",
    "app",
    "renderer",
]

[patch.crates-io]
yew = { git = "https://github.com/yewstack/yew", rev = "6f6519dab4c5990029fe8d85c47daf439fdc3988" }
yew-agent = { git = "https://github.com/yewstack/yew", rev = "6f6519dab4c5990029fe8d85c47daf439fdc3988" }

[profile.dev.package.'*']
opt-level = 3

[profile.dev.package.oort_renderer]
opt-level = 1

[profile.dev]
opt-level = 0

[profile.release]
debug = true
lto = true

[profile.bench]
debug = true
lto = false
