[package]
name = "oort_version_control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
idb = "0.4.1"
js-sys = "0.3.63"
log = "0.4.18"
serde = { version = "1.0.163", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
sha2 = "0.10.6"
wasm-bindgen = "0.2.86"
