[package]
name = "oort-app"
version = "0.9.0"
edition = "2021"
build = "build.rs"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oort_renderer = { path = "../renderer" }
oort_simulation_worker = { path = "../simulation_worker" }
oort_analyzer_worker = { path = "../analyzer_worker" }
oort_simulator = { path = "../../shared/simulator", features = ["js"], default-features = false }
oort_telemetry_proto = { path = "../../shared/telemetry_proto" }
bincode = "1.3.3"
chrono = "0.4.19"
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
flate2 = "1.0.24"
getrandom = { version = "0.2.6", features = ["js"] }
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
js-sys = "0.3.57"
log = "0.4.17"
memoffset = "0.6.5"
nalgebra = { version = "0.31.0", features = ["serde-serialize"] }
no-comment = "0.0.3"
petname = "1.1.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_seeder = "0.2.3"
rbtag = "0.3.0"
regex = "1.5.6"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
yew = { version = "0.19.3", features = ["csr"] }
yew-agent = "0.1.0"
gloo-render = "0.1.1"
reqwasm = "0.5.0"
wasm-bindgen-futures = "0.4.30"
monaco = { version = "0.3.0", features = ["yew-components"] }
yew-router = "0.16"
sha2 = "0.10.2"
qstring = "0.7.2"
prettyplease = "0.1"
syn = { version = "1", default-features = false, features = ["full", "parsing"] }
gloo-utils = "0.1.5"
gloo-timers = "0.2.4"

[dependencies.web-sys]
version = "0.3.57"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'HtmlCanvasElement',
  'Node',
  'Window',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGl2RenderingContext',
  'WebGlShader',
  'WebGlUniformLocation',
  'KeyboardEvent',
  'console',
  'Storage',
  'WheelEvent',
  'MouseEvent',
  'Request',
  'EventTarget',
]

[build-dependencies]
built = { version = "0.5", features = ["git2", "chrono", "semver"] }
