[package]
name = "oort_compiler"
version = "0.52.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.69"
tempdir = "0.3.7"
glob = "0.3.1"
log = "0.4.17"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }

[[bench]]
name = "compiler"
harness = false
