[workspace]
resolver = "2"

members = [
    "compiler",
    "telemetry",
    "leaderboard",
]

[profile.dev.package.'*']
opt-level = "s"

[profile.dev]
opt-level = 0

[profile.release]
debug = false
lto = false
opt-level = "s"

[profile.bench]
debug = true
lto = false
opt-level = "s"
