[package]
name = "oort_server"
version = "0.4.1"
publish = false
edition = "2021"

[dependencies]
salvo = "0.25"
salvo_extra = { version="0.25", features=["cors"] }
tokio = { version = "1", features = ["macros", "process"] }
anyhow = "1.0"
bytes = "1.1"
log = "0.4.17"
stackdriver_logger = "0.8.0"
