[package]
name = "oort_server"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
salvo = "0.25"
tokio = { version = "1", features = ["macros"] }
pretty_env_logger = "0.2.3"
anyhow = "1.0"
bytes = "1.1"
log = "0.4.17"
