[package]
name = "oort_code_encryption"
version = "0.36.0"
publish = false
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10.1", features = ["std"] }
anyhow = "1.0.68"
base64 = "0.21.0"
bincode = "1.3.3"
flate2 = "1.0.25"
rand = "0.8.5"
serde = "1.0.152"
sha2 = "0.10.6"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "benchmark"
harness = false
