[package]
name = "oort_worker"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oort_simulator = { path = "../simulator" }
yew = "0.19"
yew-agent = "0.1"
serde = "*"
