[package]
name = "oort_worker"
version = "0.1.0"
edition = "2021"

[dependencies]
oort_simulator = { path = "../simulator" }
yew = "0.19"
yew-agent = "0.1"
serde = "1.0"
console_log = "0.2.0"
log = "0.4"
