[package]
name = "oort_tools"
version = "0.34.1"
publish = false
edition = "2021"
resolver = "2"

[dependencies]
oort_proto = { path = "../shared/proto" }
oort_simulator = { path = "../shared/simulator" }
firestore = "0.6.1"
gcloud-sdk = "0.18.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.20", features = ["full"] }
log = "0.4.17"
env_logger = "0.9.0"
reqwest = { version = "0.11.11", features = ["json"] }
rayon = "1.5.3"
serde_json = "1.0"
chrono = "0.4.22"
clap = { version = "3.2.22", features = ["derive"] }
skillratings = "0.12.0"
itertools = "0.10.5"
comfy-table = "6.1.0"
petname = "1.1.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_seeder = "0.2.3"
rusqlite = { version = "0.28.0", features = ["bundled"] }
anyhow = "1.0.68"
shell-words = "1.1.0"
toml = "0.7.0"
indicatif = { version = "0.17.3", features = ["tokio"] }
once_cell = "1.17.0"

[patch.crates-io]
rand_seeder = { git = "https://github.com/rlane/seeder", rev = "c39e58447f7c236fb98579a5d46e5668b92a3245" }

[profile.dev.package.'*']
opt-level = 3

[profile.dev]
opt-level = 0

[profile.release]
debug = true
lto = "thin"

[profile.bench]
debug = true
lto = "thin"
