name: check
permissions:
  contents: read
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo check
      - run: cargo check --manifest-path=frontend/Cargo.toml --target=wasm32-unknown-unknown
      - run: cargo test
